[Bug] Remove Authorization header in signin request
BuildForSDG/Team-226-Frontend pull request #30
Opened 2020-06-06 21:19 UTC by Cressence

## Description
A condition to check that the authorization request shouldn't be added during signin.

Fixes #29 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

2020-06-07 04:44 UTC, wadleo requested changes
LGTM but @Cressence can you check if the other auth endpoints have this issue, thanks.

2020-06-08 09:27 UTC, sonegillis submitted a review, later dismissed

2020-06-08 13:23 UTC, gastonche approved these changes

2020-06-08 13:40 UTC, sonegillis approved these changes

2020-06-09 10:24 UTC, wadleo approved these changes
LGTM me, hope @Cressence it's properly tested, thanks for the nice fix.

2020-06-09 10:25 UTC, sonegillis approved these changes

2020-06-10 08:09 UTC, merged